### ISSUE TITLE
Update perl-languageserver to support perl.disableCache

### ISSUE THREAD

**Issue by Freed-Wu** [bmeneg/coc-perl#17] opened 2023-01-11 19:09 UTC
TIA!

**Comment by Freed-Wu** [comment] 2023-02-25 10:36
It looks like due to <https://github.com/richterger/Perl-LanguageServer/blob/6d2dbfa8051da15eb5728629f9bc89876650bebd/lib/Perl/LanguageServer/Workspace.pm#L147>

**Comment by bmeneg** [comment] 2023-07-06 21:40
Hey @Freed-Wu, sorry for the so-late reply.
You only need to set `perl.disableCache` to `true` on `coc-extension.json` file.
AFAIK it's working as designed from `coc-perl` perspective.

**Comment by Freed-Wu** [comment] 2023-07-06 22:09
Coc.nvim give a warning:

![image](https://github.com/bmeneg/coc-perl/assets/32936898/b59abc1b-9a21-4dbc-b530-53373e8a5298)

**Comment by bmeneg** [comment] 2023-07-06 22:56
Hmm. I'll investigate why this warning is popping up, because I saw other properties with the same error, but they were working just fine in the language server side. I need to create a full set of tests for each (or, at least, most of) option, since some won't really work due to the lack of DAP (debug adapter protocol) on `coc-nvim`.

I'll dive into it. Thanks for the report and feedback so far.

**Comment by bmeneg** [comment] 2023-07-07 18:33
@Freed-Wu it should be fixed now. I just merged #22 containing the fix.

**Closed as completed** 2023-07-08 01:33 UTC
Labels: bug
