### ISSUE TITLE
LSP server crashes when opening two different perl files in neovim

### ISSUE THREAD

**Issue by sdondley** [bmeneg/coc-perl#15] opened 2022-02-27 18:01 UTC
Title about covers it.

I'm new to LSPs and coc so it's probably some basic misconfiguration on my end but can't find anything that might help address this problem.

Using neovim 0.6.1 with latest version of coc. coc-perl installed with CocInstall.

**Comment by bmeneg** [comment] 2022-11-02 15:15
Hi @sdondley, I'm very sorry for the months of delay.

I've tested locally, and it didn't crash, running neovim 0.6.1 too.
When it crashes, do you see any message errors or something like that?
That's very likely the issue is in the actual language server (https://github.com/richterger/Perl-LanguageServer), but it would be really helpful any error message or something like that.

**Comment by bmeneg** [comment] 2022-11-18 17:15
@sdondley, it seems the issue was solved in the new release by https://github.com/richterger/Perl-LanguageServer/issues/155.
Since it has been quite some time since you opened this issue and it was not really related to the coc-perl plugin, I'm going to close this issue.

But please, feel free to reopen it or create a new one in case things keep crashing.

Thanks!

**Closed as completed by bmeneg** 2022-11-18 17:15 UTC
